### ISSUE TITLE
Create Contributing Guidelines

### ISSUE THREAD

**Issue by iiKoe** [iiKoe/bustamove#28]
Create a contributing.md

https://github.com/blog/1184-contributing-guidelines

**Comment by iiKoe** [comment]
Possible rule for Pull request approval (person in order of arrival/check time):
_Person 1_: Checks the code quality **AND** Checks out the branch to see if it works
_Person 2_: Checks the code quality

_Person 1_: Requests changes if needed, **ONLY** approves when there either no issues, or there are only trivial **style** issues (i.e. comments, indentation)
_Person 2_: Can only approve when there are **NO issues**

**Comment by 11maxed11** [comment]
This contribution document states the general rules for contributing to this project. It divides pull requests into the 5 following categories:

(1) Normal pull requests:
Normal pull request must be reviewed by at least 2 members of the group. This includes the addition of new classes, features, enhancements, and bug fixes that interfere with many classes; namely two other members classes.
The two reviewers must check the code quality, and approve ONLY if everything is okay, and the submitter have responded to their comments, if any.
-- If a reviewer finds necessary, he can double check that the game works completely fine on his computer i.e. all good and Grade builds. When so, he must mention this in his feedback.


(2) Simple pull requests:
Simple pulls are small in size and include only trivial changes. This includes fixing issues and bugs related to the requester's own class or only one another member class.
For a pull to be considered simple, the requester must mention this in the pull description, and assign one reviewer. If the request concerns only one team member code, he should be tagged. If it concerns the requester's previous code, a free team member should be tagged to approve it. 


(3) Assignments submissions to develop branch:
Two reviewers must check the submission, make sure it's the latest updated version of the assignment, and approve this.


(4) From develop to MASTER branch
This pull is usually done when the group wants to submit the assignments and mark a release every Friday. Based on this, as long as the purpose is the one mentioned, a member is free to pull and merge on his own. If the purpose isn't the one mentioned above, this release is treated as a Normal pull request.


(4) TA pull requests:
Pull requests made by the TA generally involve adding the .md files of assignment grading and his feedback. All three members should approve this pull request. This is to make sure that everyone is continent with the grade and the grading scheme, as merging this pull implies everyone is so.
This will help maximize the grade and annoy the TA :>


## General Rules ##
(1) When submitting a commit that helps fix a stated issue, please make sure to mention the issue number in that commit in a way that Github will detect and delete the issue. If preferred, one is free to delete the issue manually.
(2) Submissions are allowed only after checking that Gradle builds correctly, and no tool errors exist.
(3) When in doubt, feel free request changes to any pull. Pulls with requested changes MUST NOT be merged.

**Comment by 11maxed11** [comment]
^^ Please review the above draft and mention any comments. This was written to allow maximum flexibility and minimize useless approvals.
