### ISSUE TITLE
Level 1: the yellow line doesn't pop when it should be

### ISSUE THREAD

**Issue by 11maxed11** [iiKoe/bustamove#30]
- As far as of the testing that was carried on, this happens only when the first shot ball is yellow (And it snaps in the correct location that causes the full line pop).
- In this case, the balls pop animation works, and but the yellow balls don't disappear.

**Comment by jeroenoverman** [comment]
fixed in merge https://github.com/iiKoe/bustamove/commit/e4ebfb66f2617273432b2703875e4ff54025148c
