### ISSUE TITLE
The game sometimes randomly loads a level when you are playing a level

### ISSUE THREAD

**Issue by jeroenoverman** [iiKoe/bustamove#72]
When you play a random level, the game sometimes generates a new level while you are playing it

**Comment by jeroenoverman** [comment]
Apparently the menu buttons still work when you are in another screen.

**Comment by 11maxed11** [comment]
Based on some review I did following Jeroen's suggestion, it looks like that the Stage object in the MainMenuScreen isn't being disposed of after the menu is not loaded anymore. I suggest we create a dispose function for each screen that disposes of the previously created objects in that screen whenever it's not needed anymore. Please check the libgdx Screen API for any already available methods.
